name: Publish Docs

on:
  push:
    branches:
      - master
    tags:
      - 'v*'

jobs:
  docs:
    runs-on: ubuntu-20.04
    steps:
      - name: '📥 Checkout repository'
        uses: actions/checkout@v2

      - name: '🔧 Build emanote site'
        run: |
          cd docs
          mkdir -p output.docker
          docker run -e LANG=C.UTF-8 -e LC_ALL=C.UTF-8 -v $PWD:/data sridca/emanote emanote --layers "/data;/data/.deploy/github" gen /data/output.docker
          cp -r output.docker ../_build  # Ditch docker created root-owned files
          bash ../_build/_emanote-bin/compile-css

      - name: '📸 Build Documentation'
        id: build
        run: |
          if [[ $GITHUB_REF =~ ^refs/tags/v ]]; then
            tag="${GITHUB_REF/refs\/tags\//}"
            commit_message="Release $tag"
          else
            tag=""
            commit_message="$default_commit_message"
          fi
          echo "::set-output name=commit_message::$commit_message"

          ./scripts/gh/update-docs.sh _build $tag
        env:
          default_commit_message: |
            docs: ${{ github.event.head_commit.message }}

            Source commit: ${{ github.sha }}

      - name: '📘 Publish'
        if: ${{ github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/v') }}
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.WILLIAM_KING_TOKEN }}
          enable_jekyll: false
          publish_dir: _build
          keep_files: true
          user_name: 'William King Noel Bot'
          user_email: 'adrestia@iohk.io'
          full_commit_message: ${{ steps.build.outputs.commit_message }}
